package com.shanghai.dao.base;

import com.shanghai.domain.base.GhCurrentProducts;

public interface GhCurrentProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gh_current_products
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ghCurrentProductsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gh_current_products
     *
     * @mbggenerated
     */
    int insert(GhCurrentProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gh_current_products
     *
     * @mbggenerated
     */
    int insertSelective(GhCurrentProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gh_current_products
     *
     * @mbggenerated
     */
    GhCurrentProducts selectByPrimaryKey(String ghCurrentProductsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gh_current_products
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GhCurrentProducts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gh_current_products
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GhCurrentProducts record);
}