package com.shanghai.dao.base;

import com.shanghai.domain.UserDomain;

public interface UserDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon May 29 11:23:47 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon May 29 11:23:47 CST 2017
     */
    int insert(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon May 29 11:23:47 CST 2017
     */
    int insertSelective(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon May 29 11:23:47 CST 2017
     */
    UserDomain selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon May 29 11:23:47 CST 2017
     */
    int updateByPrimaryKeySelective(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon May 29 11:23:47 CST 2017
     */
    int updateByPrimaryKey(UserDomain record);
}