package com.shanghai.domain.base;

import java.math.BigDecimal;
import java.util.Date;

public class GhCurrentProducts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.gh_current_products_id
     *
     * @mbggenerated
     */
    private String ghCurrentProductsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.product_oid
     *
     * @mbggenerated
     */
    private String productOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.asset_pool_oid
     *
     * @mbggenerated
     */
    private String assetPoolOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.spv_oid
     *
     * @mbggenerated
     */
    private String spvOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.full_name
     *
     * @mbggenerated
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.administrator
     *
     * @mbggenerated
     */
    private String administrator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.reveal
     *
     * @mbggenerated
     */
    private String reveal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.reveal_comment
     *
     * @mbggenerated
     */
    private String revealComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.income_calc_basis
     *
     * @mbggenerated
     */
    private String incomeCalcBasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.operation_rate
     *
     * @mbggenerated
     */
    private BigDecimal operationRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.accrual_cycle_oid
     *
     * @mbggenerated
     */
    private String accrualCycleOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.raise_start_date_type
     *
     * @mbggenerated
     */
    private String raiseStartDateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.raise_start_date
     *
     * @mbggenerated
     */
    private Date raiseStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.raise_period_days
     *
     * @mbggenerated
     */
    private Integer raisePeriodDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.lock_period_days
     *
     * @mbggenerated
     */
    private Integer lockPeriodDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.interests_first_days
     *
     * @mbggenerated
     */
    private Integer interestsFirstDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.duration_period_days
     *
     * @mbggenerated
     */
    private Integer durationPeriodDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.exp_aror
     *
     * @mbggenerated
     */
    private BigDecimal expAror;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.exp_aror_sec
     *
     * @mbggenerated
     */
    private BigDecimal expArorSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.basic_ratio
     *
     * @mbggenerated
     */
    private BigDecimal basicRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.reward_interest
     *
     * @mbggenerated
     */
    private BigDecimal rewardInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.netUnit_share
     *
     * @mbggenerated
     */
    private BigDecimal netunitShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.invest_min
     *
     * @mbggenerated
     */
    private BigDecimal investMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.invest_additional
     *
     * @mbggenerated
     */
    private BigDecimal investAdditional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.invest_max
     *
     * @mbggenerated
     */
    private BigDecimal investMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.invest_date_type
     *
     * @mbggenerated
     */
    private String investDateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.min_rredeem
     *
     * @mbggenerated
     */
    private BigDecimal minRredeem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.max_redeem
     *
     * @mbggenerated
     */
    private BigDecimal maxRedeem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.additional_rredeem
     *
     * @mbggenerated
     */
    private BigDecimal additionalRredeem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.redeem_date_type
     *
     * @mbggenerated
     */
    private String redeemDateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.net_max_rredeem_day
     *
     * @mbggenerated
     */
    private BigDecimal netMaxRredeemDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.daily_net_max_rredeem
     *
     * @mbggenerated
     */
    private BigDecimal dailyNetMaxRredeem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.max_hold
     *
     * @mbggenerated
     */
    private BigDecimal maxHold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.single_daily_max_redeem
     *
     * @mbggenerated
     */
    private BigDecimal singleDailyMaxRedeem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.accrual_repay_days
     *
     * @mbggenerated
     */
    private Integer accrualRepayDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.purchase_confirm_days
     *
     * @mbggenerated
     */
    private Integer purchaseConfirmDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.redeem_confirm_days
     *
     * @mbggenerated
     */
    private Integer redeemConfirmDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.setup_date_type
     *
     * @mbggenerated
     */
    private String setupDateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.setup_date
     *
     * @mbggenerated
     */
    private Date setupDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.invest_comment
     *
     * @mbggenerated
     */
    private String investComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.instruction
     *
     * @mbggenerated
     */
    private String instruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.risk_level
     *
     * @mbggenerated
     */
    private String riskLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.investor_level
     *
     * @mbggenerated
     */
    private String investorLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.file_keys
     *
     * @mbggenerated
     */
    private String fileKeys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.raise_end_date
     *
     * @mbggenerated
     */
    private Date raiseEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.raise_fail_date
     *
     * @mbggenerated
     */
    private Date raiseFailDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.duration_period_end_date
     *
     * @mbggenerated
     */
    private Date durationPeriodEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.audit_state
     *
     * @mbggenerated
     */
    private String auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.raised_total_number
     *
     * @mbggenerated
     */
    private BigDecimal raisedTotalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.currentVolume
     *
     * @mbggenerated
     */
    private BigDecimal currentvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.previous_curVolume
     *
     * @mbggenerated
     */
    private BigDecimal previousCurvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.previous_curVolume_percent
     *
     * @mbggenerated
     */
    private BigDecimal previousCurvolumePercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.is_previous_curVolume
     *
     * @mbggenerated
     */
    private String isPreviousCurvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.collectedVolume
     *
     * @mbggenerated
     */
    private BigDecimal collectedvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.max_saleVolume
     *
     * @mbggenerated
     */
    private BigDecimal maxSalevolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.lock_collectedVolume
     *
     * @mbggenerated
     */
    private BigDecimal lockCollectedvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.repay_date
     *
     * @mbggenerated
     */
    private Date repayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.repay_interest_status
     *
     * @mbggenerated
     */
    private String repayInterestStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.repay_loan_status
     *
     * @mbggenerated
     */
    private String repayLoanStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.newest_profit_confirm_date
     *
     * @mbggenerated
     */
    private Date newestProfitConfirmDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.invest_file_key
     *
     * @mbggenerated
     */
    private String investFileKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.service_file_key
     *
     * @mbggenerated
     */
    private String serviceFileKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.is_open_purchase
     *
     * @mbggenerated
     */
    private String isOpenPurchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.is_open_remeed
     *
     * @mbggenerated
     */
    private String isOpenRemeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.purchase_apply_status
     *
     * @mbggenerated
     */
    private String purchaseApplyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.redeem_apply_status
     *
     * @mbggenerated
     */
    private String redeemApplyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.clearing_time
     *
     * @mbggenerated
     */
    private String clearingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.cleared_time
     *
     * @mbggenerated
     */
    private String clearedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.deal_start_time
     *
     * @mbggenerated
     */
    private String dealStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.deal_end_time
     *
     * @mbggenerated
     */
    private String dealEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.purchase_people_num
     *
     * @mbggenerated
     */
    private Integer purchasePeopleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.purchase_num
     *
     * @mbggenerated
     */
    private Integer purchaseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.single_day_redeem_count
     *
     * @mbggenerated
     */
    private Integer singleDayRedeemCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.clearing_operator
     *
     * @mbggenerated
     */
    private String clearingOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.rec_period_exp_anYield
     *
     * @mbggenerated
     */
    private BigDecimal recPeriodExpAnyield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.raise_full_found_type
     *
     * @mbggenerated
     */
    private String raiseFullFoundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.auto_found_days
     *
     * @mbggenerated
     */
    private Integer autoFoundDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.overdue_status
     *
     * @mbggenerated
     */
    private String overdueStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.redeemWithout_interest
     *
     * @mbggenerated
     */
    private String redeemwithoutInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.closing_rule
     *
     * @mbggenerated
     */
    private String closingRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.market_state
     *
     * @mbggenerated
     */
    private String marketState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.project_id
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gh_current_products.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.gh_current_products_id
     *
     * @return the value of t_gh_current_products.gh_current_products_id
     *
     * @mbggenerated
     */
    public String getGhCurrentProductsId() {
        return ghCurrentProductsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.gh_current_products_id
     *
     * @param ghCurrentProductsId the value for t_gh_current_products.gh_current_products_id
     *
     * @mbggenerated
     */
    public void setGhCurrentProductsId(String ghCurrentProductsId) {
        this.ghCurrentProductsId = ghCurrentProductsId == null ? null : ghCurrentProductsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.product_oid
     *
     * @return the value of t_gh_current_products.product_oid
     *
     * @mbggenerated
     */
    public String getProductOid() {
        return productOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.product_oid
     *
     * @param productOid the value for t_gh_current_products.product_oid
     *
     * @mbggenerated
     */
    public void setProductOid(String productOid) {
        this.productOid = productOid == null ? null : productOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.asset_pool_oid
     *
     * @return the value of t_gh_current_products.asset_pool_oid
     *
     * @mbggenerated
     */
    public String getAssetPoolOid() {
        return assetPoolOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.asset_pool_oid
     *
     * @param assetPoolOid the value for t_gh_current_products.asset_pool_oid
     *
     * @mbggenerated
     */
    public void setAssetPoolOid(String assetPoolOid) {
        this.assetPoolOid = assetPoolOid == null ? null : assetPoolOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.spv_oid
     *
     * @return the value of t_gh_current_products.spv_oid
     *
     * @mbggenerated
     */
    public String getSpvOid() {
        return spvOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.spv_oid
     *
     * @param spvOid the value for t_gh_current_products.spv_oid
     *
     * @mbggenerated
     */
    public void setSpvOid(String spvOid) {
        this.spvOid = spvOid == null ? null : spvOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.code
     *
     * @return the value of t_gh_current_products.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.code
     *
     * @param code the value for t_gh_current_products.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.name
     *
     * @return the value of t_gh_current_products.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.name
     *
     * @param name the value for t_gh_current_products.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.full_name
     *
     * @return the value of t_gh_current_products.full_name
     *
     * @mbggenerated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.full_name
     *
     * @param fullName the value for t_gh_current_products.full_name
     *
     * @mbggenerated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.administrator
     *
     * @return the value of t_gh_current_products.administrator
     *
     * @mbggenerated
     */
    public String getAdministrator() {
        return administrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.administrator
     *
     * @param administrator the value for t_gh_current_products.administrator
     *
     * @mbggenerated
     */
    public void setAdministrator(String administrator) {
        this.administrator = administrator == null ? null : administrator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.type
     *
     * @return the value of t_gh_current_products.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.type
     *
     * @param type the value for t_gh_current_products.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.reveal
     *
     * @return the value of t_gh_current_products.reveal
     *
     * @mbggenerated
     */
    public String getReveal() {
        return reveal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.reveal
     *
     * @param reveal the value for t_gh_current_products.reveal
     *
     * @mbggenerated
     */
    public void setReveal(String reveal) {
        this.reveal = reveal == null ? null : reveal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.reveal_comment
     *
     * @return the value of t_gh_current_products.reveal_comment
     *
     * @mbggenerated
     */
    public String getRevealComment() {
        return revealComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.reveal_comment
     *
     * @param revealComment the value for t_gh_current_products.reveal_comment
     *
     * @mbggenerated
     */
    public void setRevealComment(String revealComment) {
        this.revealComment = revealComment == null ? null : revealComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.currency
     *
     * @return the value of t_gh_current_products.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.currency
     *
     * @param currency the value for t_gh_current_products.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.income_calc_basis
     *
     * @return the value of t_gh_current_products.income_calc_basis
     *
     * @mbggenerated
     */
    public String getIncomeCalcBasis() {
        return incomeCalcBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.income_calc_basis
     *
     * @param incomeCalcBasis the value for t_gh_current_products.income_calc_basis
     *
     * @mbggenerated
     */
    public void setIncomeCalcBasis(String incomeCalcBasis) {
        this.incomeCalcBasis = incomeCalcBasis == null ? null : incomeCalcBasis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.operation_rate
     *
     * @return the value of t_gh_current_products.operation_rate
     *
     * @mbggenerated
     */
    public BigDecimal getOperationRate() {
        return operationRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.operation_rate
     *
     * @param operationRate the value for t_gh_current_products.operation_rate
     *
     * @mbggenerated
     */
    public void setOperationRate(BigDecimal operationRate) {
        this.operationRate = operationRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.accrual_cycle_oid
     *
     * @return the value of t_gh_current_products.accrual_cycle_oid
     *
     * @mbggenerated
     */
    public String getAccrualCycleOid() {
        return accrualCycleOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.accrual_cycle_oid
     *
     * @param accrualCycleOid the value for t_gh_current_products.accrual_cycle_oid
     *
     * @mbggenerated
     */
    public void setAccrualCycleOid(String accrualCycleOid) {
        this.accrualCycleOid = accrualCycleOid == null ? null : accrualCycleOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.raise_start_date_type
     *
     * @return the value of t_gh_current_products.raise_start_date_type
     *
     * @mbggenerated
     */
    public String getRaiseStartDateType() {
        return raiseStartDateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.raise_start_date_type
     *
     * @param raiseStartDateType the value for t_gh_current_products.raise_start_date_type
     *
     * @mbggenerated
     */
    public void setRaiseStartDateType(String raiseStartDateType) {
        this.raiseStartDateType = raiseStartDateType == null ? null : raiseStartDateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.raise_start_date
     *
     * @return the value of t_gh_current_products.raise_start_date
     *
     * @mbggenerated
     */
    public Date getRaiseStartDate() {
        return raiseStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.raise_start_date
     *
     * @param raiseStartDate the value for t_gh_current_products.raise_start_date
     *
     * @mbggenerated
     */
    public void setRaiseStartDate(Date raiseStartDate) {
        this.raiseStartDate = raiseStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.raise_period_days
     *
     * @return the value of t_gh_current_products.raise_period_days
     *
     * @mbggenerated
     */
    public Integer getRaisePeriodDays() {
        return raisePeriodDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.raise_period_days
     *
     * @param raisePeriodDays the value for t_gh_current_products.raise_period_days
     *
     * @mbggenerated
     */
    public void setRaisePeriodDays(Integer raisePeriodDays) {
        this.raisePeriodDays = raisePeriodDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.lock_period_days
     *
     * @return the value of t_gh_current_products.lock_period_days
     *
     * @mbggenerated
     */
    public Integer getLockPeriodDays() {
        return lockPeriodDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.lock_period_days
     *
     * @param lockPeriodDays the value for t_gh_current_products.lock_period_days
     *
     * @mbggenerated
     */
    public void setLockPeriodDays(Integer lockPeriodDays) {
        this.lockPeriodDays = lockPeriodDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.interests_first_days
     *
     * @return the value of t_gh_current_products.interests_first_days
     *
     * @mbggenerated
     */
    public Integer getInterestsFirstDays() {
        return interestsFirstDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.interests_first_days
     *
     * @param interestsFirstDays the value for t_gh_current_products.interests_first_days
     *
     * @mbggenerated
     */
    public void setInterestsFirstDays(Integer interestsFirstDays) {
        this.interestsFirstDays = interestsFirstDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.duration_period_days
     *
     * @return the value of t_gh_current_products.duration_period_days
     *
     * @mbggenerated
     */
    public Integer getDurationPeriodDays() {
        return durationPeriodDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.duration_period_days
     *
     * @param durationPeriodDays the value for t_gh_current_products.duration_period_days
     *
     * @mbggenerated
     */
    public void setDurationPeriodDays(Integer durationPeriodDays) {
        this.durationPeriodDays = durationPeriodDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.exp_aror
     *
     * @return the value of t_gh_current_products.exp_aror
     *
     * @mbggenerated
     */
    public BigDecimal getExpAror() {
        return expAror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.exp_aror
     *
     * @param expAror the value for t_gh_current_products.exp_aror
     *
     * @mbggenerated
     */
    public void setExpAror(BigDecimal expAror) {
        this.expAror = expAror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.exp_aror_sec
     *
     * @return the value of t_gh_current_products.exp_aror_sec
     *
     * @mbggenerated
     */
    public BigDecimal getExpArorSec() {
        return expArorSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.exp_aror_sec
     *
     * @param expArorSec the value for t_gh_current_products.exp_aror_sec
     *
     * @mbggenerated
     */
    public void setExpArorSec(BigDecimal expArorSec) {
        this.expArorSec = expArorSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.basic_ratio
     *
     * @return the value of t_gh_current_products.basic_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getBasicRatio() {
        return basicRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.basic_ratio
     *
     * @param basicRatio the value for t_gh_current_products.basic_ratio
     *
     * @mbggenerated
     */
    public void setBasicRatio(BigDecimal basicRatio) {
        this.basicRatio = basicRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.reward_interest
     *
     * @return the value of t_gh_current_products.reward_interest
     *
     * @mbggenerated
     */
    public BigDecimal getRewardInterest() {
        return rewardInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.reward_interest
     *
     * @param rewardInterest the value for t_gh_current_products.reward_interest
     *
     * @mbggenerated
     */
    public void setRewardInterest(BigDecimal rewardInterest) {
        this.rewardInterest = rewardInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.netUnit_share
     *
     * @return the value of t_gh_current_products.netUnit_share
     *
     * @mbggenerated
     */
    public BigDecimal getNetunitShare() {
        return netunitShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.netUnit_share
     *
     * @param netunitShare the value for t_gh_current_products.netUnit_share
     *
     * @mbggenerated
     */
    public void setNetunitShare(BigDecimal netunitShare) {
        this.netunitShare = netunitShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.invest_min
     *
     * @return the value of t_gh_current_products.invest_min
     *
     * @mbggenerated
     */
    public BigDecimal getInvestMin() {
        return investMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.invest_min
     *
     * @param investMin the value for t_gh_current_products.invest_min
     *
     * @mbggenerated
     */
    public void setInvestMin(BigDecimal investMin) {
        this.investMin = investMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.invest_additional
     *
     * @return the value of t_gh_current_products.invest_additional
     *
     * @mbggenerated
     */
    public BigDecimal getInvestAdditional() {
        return investAdditional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.invest_additional
     *
     * @param investAdditional the value for t_gh_current_products.invest_additional
     *
     * @mbggenerated
     */
    public void setInvestAdditional(BigDecimal investAdditional) {
        this.investAdditional = investAdditional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.invest_max
     *
     * @return the value of t_gh_current_products.invest_max
     *
     * @mbggenerated
     */
    public BigDecimal getInvestMax() {
        return investMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.invest_max
     *
     * @param investMax the value for t_gh_current_products.invest_max
     *
     * @mbggenerated
     */
    public void setInvestMax(BigDecimal investMax) {
        this.investMax = investMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.invest_date_type
     *
     * @return the value of t_gh_current_products.invest_date_type
     *
     * @mbggenerated
     */
    public String getInvestDateType() {
        return investDateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.invest_date_type
     *
     * @param investDateType the value for t_gh_current_products.invest_date_type
     *
     * @mbggenerated
     */
    public void setInvestDateType(String investDateType) {
        this.investDateType = investDateType == null ? null : investDateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.min_rredeem
     *
     * @return the value of t_gh_current_products.min_rredeem
     *
     * @mbggenerated
     */
    public BigDecimal getMinRredeem() {
        return minRredeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.min_rredeem
     *
     * @param minRredeem the value for t_gh_current_products.min_rredeem
     *
     * @mbggenerated
     */
    public void setMinRredeem(BigDecimal minRredeem) {
        this.minRredeem = minRredeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.max_redeem
     *
     * @return the value of t_gh_current_products.max_redeem
     *
     * @mbggenerated
     */
    public BigDecimal getMaxRedeem() {
        return maxRedeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.max_redeem
     *
     * @param maxRedeem the value for t_gh_current_products.max_redeem
     *
     * @mbggenerated
     */
    public void setMaxRedeem(BigDecimal maxRedeem) {
        this.maxRedeem = maxRedeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.additional_rredeem
     *
     * @return the value of t_gh_current_products.additional_rredeem
     *
     * @mbggenerated
     */
    public BigDecimal getAdditionalRredeem() {
        return additionalRredeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.additional_rredeem
     *
     * @param additionalRredeem the value for t_gh_current_products.additional_rredeem
     *
     * @mbggenerated
     */
    public void setAdditionalRredeem(BigDecimal additionalRredeem) {
        this.additionalRredeem = additionalRredeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.redeem_date_type
     *
     * @return the value of t_gh_current_products.redeem_date_type
     *
     * @mbggenerated
     */
    public String getRedeemDateType() {
        return redeemDateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.redeem_date_type
     *
     * @param redeemDateType the value for t_gh_current_products.redeem_date_type
     *
     * @mbggenerated
     */
    public void setRedeemDateType(String redeemDateType) {
        this.redeemDateType = redeemDateType == null ? null : redeemDateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.net_max_rredeem_day
     *
     * @return the value of t_gh_current_products.net_max_rredeem_day
     *
     * @mbggenerated
     */
    public BigDecimal getNetMaxRredeemDay() {
        return netMaxRredeemDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.net_max_rredeem_day
     *
     * @param netMaxRredeemDay the value for t_gh_current_products.net_max_rredeem_day
     *
     * @mbggenerated
     */
    public void setNetMaxRredeemDay(BigDecimal netMaxRredeemDay) {
        this.netMaxRredeemDay = netMaxRredeemDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.daily_net_max_rredeem
     *
     * @return the value of t_gh_current_products.daily_net_max_rredeem
     *
     * @mbggenerated
     */
    public BigDecimal getDailyNetMaxRredeem() {
        return dailyNetMaxRredeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.daily_net_max_rredeem
     *
     * @param dailyNetMaxRredeem the value for t_gh_current_products.daily_net_max_rredeem
     *
     * @mbggenerated
     */
    public void setDailyNetMaxRredeem(BigDecimal dailyNetMaxRredeem) {
        this.dailyNetMaxRredeem = dailyNetMaxRredeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.max_hold
     *
     * @return the value of t_gh_current_products.max_hold
     *
     * @mbggenerated
     */
    public BigDecimal getMaxHold() {
        return maxHold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.max_hold
     *
     * @param maxHold the value for t_gh_current_products.max_hold
     *
     * @mbggenerated
     */
    public void setMaxHold(BigDecimal maxHold) {
        this.maxHold = maxHold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.single_daily_max_redeem
     *
     * @return the value of t_gh_current_products.single_daily_max_redeem
     *
     * @mbggenerated
     */
    public BigDecimal getSingleDailyMaxRedeem() {
        return singleDailyMaxRedeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.single_daily_max_redeem
     *
     * @param singleDailyMaxRedeem the value for t_gh_current_products.single_daily_max_redeem
     *
     * @mbggenerated
     */
    public void setSingleDailyMaxRedeem(BigDecimal singleDailyMaxRedeem) {
        this.singleDailyMaxRedeem = singleDailyMaxRedeem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.accrual_repay_days
     *
     * @return the value of t_gh_current_products.accrual_repay_days
     *
     * @mbggenerated
     */
    public Integer getAccrualRepayDays() {
        return accrualRepayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.accrual_repay_days
     *
     * @param accrualRepayDays the value for t_gh_current_products.accrual_repay_days
     *
     * @mbggenerated
     */
    public void setAccrualRepayDays(Integer accrualRepayDays) {
        this.accrualRepayDays = accrualRepayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.purchase_confirm_days
     *
     * @return the value of t_gh_current_products.purchase_confirm_days
     *
     * @mbggenerated
     */
    public Integer getPurchaseConfirmDays() {
        return purchaseConfirmDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.purchase_confirm_days
     *
     * @param purchaseConfirmDays the value for t_gh_current_products.purchase_confirm_days
     *
     * @mbggenerated
     */
    public void setPurchaseConfirmDays(Integer purchaseConfirmDays) {
        this.purchaseConfirmDays = purchaseConfirmDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.redeem_confirm_days
     *
     * @return the value of t_gh_current_products.redeem_confirm_days
     *
     * @mbggenerated
     */
    public Integer getRedeemConfirmDays() {
        return redeemConfirmDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.redeem_confirm_days
     *
     * @param redeemConfirmDays the value for t_gh_current_products.redeem_confirm_days
     *
     * @mbggenerated
     */
    public void setRedeemConfirmDays(Integer redeemConfirmDays) {
        this.redeemConfirmDays = redeemConfirmDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.setup_date_type
     *
     * @return the value of t_gh_current_products.setup_date_type
     *
     * @mbggenerated
     */
    public String getSetupDateType() {
        return setupDateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.setup_date_type
     *
     * @param setupDateType the value for t_gh_current_products.setup_date_type
     *
     * @mbggenerated
     */
    public void setSetupDateType(String setupDateType) {
        this.setupDateType = setupDateType == null ? null : setupDateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.setup_date
     *
     * @return the value of t_gh_current_products.setup_date
     *
     * @mbggenerated
     */
    public Date getSetupDate() {
        return setupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.setup_date
     *
     * @param setupDate the value for t_gh_current_products.setup_date
     *
     * @mbggenerated
     */
    public void setSetupDate(Date setupDate) {
        this.setupDate = setupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.invest_comment
     *
     * @return the value of t_gh_current_products.invest_comment
     *
     * @mbggenerated
     */
    public String getInvestComment() {
        return investComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.invest_comment
     *
     * @param investComment the value for t_gh_current_products.invest_comment
     *
     * @mbggenerated
     */
    public void setInvestComment(String investComment) {
        this.investComment = investComment == null ? null : investComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.instruction
     *
     * @return the value of t_gh_current_products.instruction
     *
     * @mbggenerated
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.instruction
     *
     * @param instruction the value for t_gh_current_products.instruction
     *
     * @mbggenerated
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.risk_level
     *
     * @return the value of t_gh_current_products.risk_level
     *
     * @mbggenerated
     */
    public String getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.risk_level
     *
     * @param riskLevel the value for t_gh_current_products.risk_level
     *
     * @mbggenerated
     */
    public void setRiskLevel(String riskLevel) {
        this.riskLevel = riskLevel == null ? null : riskLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.investor_level
     *
     * @return the value of t_gh_current_products.investor_level
     *
     * @mbggenerated
     */
    public String getInvestorLevel() {
        return investorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.investor_level
     *
     * @param investorLevel the value for t_gh_current_products.investor_level
     *
     * @mbggenerated
     */
    public void setInvestorLevel(String investorLevel) {
        this.investorLevel = investorLevel == null ? null : investorLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.file_keys
     *
     * @return the value of t_gh_current_products.file_keys
     *
     * @mbggenerated
     */
    public String getFileKeys() {
        return fileKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.file_keys
     *
     * @param fileKeys the value for t_gh_current_products.file_keys
     *
     * @mbggenerated
     */
    public void setFileKeys(String fileKeys) {
        this.fileKeys = fileKeys == null ? null : fileKeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.state
     *
     * @return the value of t_gh_current_products.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.state
     *
     * @param state the value for t_gh_current_products.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.operator
     *
     * @return the value of t_gh_current_products.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.operator
     *
     * @param operator the value for t_gh_current_products.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.raise_end_date
     *
     * @return the value of t_gh_current_products.raise_end_date
     *
     * @mbggenerated
     */
    public Date getRaiseEndDate() {
        return raiseEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.raise_end_date
     *
     * @param raiseEndDate the value for t_gh_current_products.raise_end_date
     *
     * @mbggenerated
     */
    public void setRaiseEndDate(Date raiseEndDate) {
        this.raiseEndDate = raiseEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.raise_fail_date
     *
     * @return the value of t_gh_current_products.raise_fail_date
     *
     * @mbggenerated
     */
    public Date getRaiseFailDate() {
        return raiseFailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.raise_fail_date
     *
     * @param raiseFailDate the value for t_gh_current_products.raise_fail_date
     *
     * @mbggenerated
     */
    public void setRaiseFailDate(Date raiseFailDate) {
        this.raiseFailDate = raiseFailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.duration_period_end_date
     *
     * @return the value of t_gh_current_products.duration_period_end_date
     *
     * @mbggenerated
     */
    public Date getDurationPeriodEndDate() {
        return durationPeriodEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.duration_period_end_date
     *
     * @param durationPeriodEndDate the value for t_gh_current_products.duration_period_end_date
     *
     * @mbggenerated
     */
    public void setDurationPeriodEndDate(Date durationPeriodEndDate) {
        this.durationPeriodEndDate = durationPeriodEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.audit_state
     *
     * @return the value of t_gh_current_products.audit_state
     *
     * @mbggenerated
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.audit_state
     *
     * @param auditState the value for t_gh_current_products.audit_state
     *
     * @mbggenerated
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.raised_total_number
     *
     * @return the value of t_gh_current_products.raised_total_number
     *
     * @mbggenerated
     */
    public BigDecimal getRaisedTotalNumber() {
        return raisedTotalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.raised_total_number
     *
     * @param raisedTotalNumber the value for t_gh_current_products.raised_total_number
     *
     * @mbggenerated
     */
    public void setRaisedTotalNumber(BigDecimal raisedTotalNumber) {
        this.raisedTotalNumber = raisedTotalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.currentVolume
     *
     * @return the value of t_gh_current_products.currentVolume
     *
     * @mbggenerated
     */
    public BigDecimal getCurrentvolume() {
        return currentvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.currentVolume
     *
     * @param currentvolume the value for t_gh_current_products.currentVolume
     *
     * @mbggenerated
     */
    public void setCurrentvolume(BigDecimal currentvolume) {
        this.currentvolume = currentvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.previous_curVolume
     *
     * @return the value of t_gh_current_products.previous_curVolume
     *
     * @mbggenerated
     */
    public BigDecimal getPreviousCurvolume() {
        return previousCurvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.previous_curVolume
     *
     * @param previousCurvolume the value for t_gh_current_products.previous_curVolume
     *
     * @mbggenerated
     */
    public void setPreviousCurvolume(BigDecimal previousCurvolume) {
        this.previousCurvolume = previousCurvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.previous_curVolume_percent
     *
     * @return the value of t_gh_current_products.previous_curVolume_percent
     *
     * @mbggenerated
     */
    public BigDecimal getPreviousCurvolumePercent() {
        return previousCurvolumePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.previous_curVolume_percent
     *
     * @param previousCurvolumePercent the value for t_gh_current_products.previous_curVolume_percent
     *
     * @mbggenerated
     */
    public void setPreviousCurvolumePercent(BigDecimal previousCurvolumePercent) {
        this.previousCurvolumePercent = previousCurvolumePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.is_previous_curVolume
     *
     * @return the value of t_gh_current_products.is_previous_curVolume
     *
     * @mbggenerated
     */
    public String getIsPreviousCurvolume() {
        return isPreviousCurvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.is_previous_curVolume
     *
     * @param isPreviousCurvolume the value for t_gh_current_products.is_previous_curVolume
     *
     * @mbggenerated
     */
    public void setIsPreviousCurvolume(String isPreviousCurvolume) {
        this.isPreviousCurvolume = isPreviousCurvolume == null ? null : isPreviousCurvolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.collectedVolume
     *
     * @return the value of t_gh_current_products.collectedVolume
     *
     * @mbggenerated
     */
    public BigDecimal getCollectedvolume() {
        return collectedvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.collectedVolume
     *
     * @param collectedvolume the value for t_gh_current_products.collectedVolume
     *
     * @mbggenerated
     */
    public void setCollectedvolume(BigDecimal collectedvolume) {
        this.collectedvolume = collectedvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.max_saleVolume
     *
     * @return the value of t_gh_current_products.max_saleVolume
     *
     * @mbggenerated
     */
    public BigDecimal getMaxSalevolume() {
        return maxSalevolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.max_saleVolume
     *
     * @param maxSalevolume the value for t_gh_current_products.max_saleVolume
     *
     * @mbggenerated
     */
    public void setMaxSalevolume(BigDecimal maxSalevolume) {
        this.maxSalevolume = maxSalevolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.lock_collectedVolume
     *
     * @return the value of t_gh_current_products.lock_collectedVolume
     *
     * @mbggenerated
     */
    public BigDecimal getLockCollectedvolume() {
        return lockCollectedvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.lock_collectedVolume
     *
     * @param lockCollectedvolume the value for t_gh_current_products.lock_collectedVolume
     *
     * @mbggenerated
     */
    public void setLockCollectedvolume(BigDecimal lockCollectedvolume) {
        this.lockCollectedvolume = lockCollectedvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.repay_date
     *
     * @return the value of t_gh_current_products.repay_date
     *
     * @mbggenerated
     */
    public Date getRepayDate() {
        return repayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.repay_date
     *
     * @param repayDate the value for t_gh_current_products.repay_date
     *
     * @mbggenerated
     */
    public void setRepayDate(Date repayDate) {
        this.repayDate = repayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.repay_interest_status
     *
     * @return the value of t_gh_current_products.repay_interest_status
     *
     * @mbggenerated
     */
    public String getRepayInterestStatus() {
        return repayInterestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.repay_interest_status
     *
     * @param repayInterestStatus the value for t_gh_current_products.repay_interest_status
     *
     * @mbggenerated
     */
    public void setRepayInterestStatus(String repayInterestStatus) {
        this.repayInterestStatus = repayInterestStatus == null ? null : repayInterestStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.repay_loan_status
     *
     * @return the value of t_gh_current_products.repay_loan_status
     *
     * @mbggenerated
     */
    public String getRepayLoanStatus() {
        return repayLoanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.repay_loan_status
     *
     * @param repayLoanStatus the value for t_gh_current_products.repay_loan_status
     *
     * @mbggenerated
     */
    public void setRepayLoanStatus(String repayLoanStatus) {
        this.repayLoanStatus = repayLoanStatus == null ? null : repayLoanStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.newest_profit_confirm_date
     *
     * @return the value of t_gh_current_products.newest_profit_confirm_date
     *
     * @mbggenerated
     */
    public Date getNewestProfitConfirmDate() {
        return newestProfitConfirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.newest_profit_confirm_date
     *
     * @param newestProfitConfirmDate the value for t_gh_current_products.newest_profit_confirm_date
     *
     * @mbggenerated
     */
    public void setNewestProfitConfirmDate(Date newestProfitConfirmDate) {
        this.newestProfitConfirmDate = newestProfitConfirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.invest_file_key
     *
     * @return the value of t_gh_current_products.invest_file_key
     *
     * @mbggenerated
     */
    public String getInvestFileKey() {
        return investFileKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.invest_file_key
     *
     * @param investFileKey the value for t_gh_current_products.invest_file_key
     *
     * @mbggenerated
     */
    public void setInvestFileKey(String investFileKey) {
        this.investFileKey = investFileKey == null ? null : investFileKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.service_file_key
     *
     * @return the value of t_gh_current_products.service_file_key
     *
     * @mbggenerated
     */
    public String getServiceFileKey() {
        return serviceFileKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.service_file_key
     *
     * @param serviceFileKey the value for t_gh_current_products.service_file_key
     *
     * @mbggenerated
     */
    public void setServiceFileKey(String serviceFileKey) {
        this.serviceFileKey = serviceFileKey == null ? null : serviceFileKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.is_open_purchase
     *
     * @return the value of t_gh_current_products.is_open_purchase
     *
     * @mbggenerated
     */
    public String getIsOpenPurchase() {
        return isOpenPurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.is_open_purchase
     *
     * @param isOpenPurchase the value for t_gh_current_products.is_open_purchase
     *
     * @mbggenerated
     */
    public void setIsOpenPurchase(String isOpenPurchase) {
        this.isOpenPurchase = isOpenPurchase == null ? null : isOpenPurchase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.is_open_remeed
     *
     * @return the value of t_gh_current_products.is_open_remeed
     *
     * @mbggenerated
     */
    public String getIsOpenRemeed() {
        return isOpenRemeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.is_open_remeed
     *
     * @param isOpenRemeed the value for t_gh_current_products.is_open_remeed
     *
     * @mbggenerated
     */
    public void setIsOpenRemeed(String isOpenRemeed) {
        this.isOpenRemeed = isOpenRemeed == null ? null : isOpenRemeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.purchase_apply_status
     *
     * @return the value of t_gh_current_products.purchase_apply_status
     *
     * @mbggenerated
     */
    public String getPurchaseApplyStatus() {
        return purchaseApplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.purchase_apply_status
     *
     * @param purchaseApplyStatus the value for t_gh_current_products.purchase_apply_status
     *
     * @mbggenerated
     */
    public void setPurchaseApplyStatus(String purchaseApplyStatus) {
        this.purchaseApplyStatus = purchaseApplyStatus == null ? null : purchaseApplyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.redeem_apply_status
     *
     * @return the value of t_gh_current_products.redeem_apply_status
     *
     * @mbggenerated
     */
    public String getRedeemApplyStatus() {
        return redeemApplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.redeem_apply_status
     *
     * @param redeemApplyStatus the value for t_gh_current_products.redeem_apply_status
     *
     * @mbggenerated
     */
    public void setRedeemApplyStatus(String redeemApplyStatus) {
        this.redeemApplyStatus = redeemApplyStatus == null ? null : redeemApplyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.clearing_time
     *
     * @return the value of t_gh_current_products.clearing_time
     *
     * @mbggenerated
     */
    public String getClearingTime() {
        return clearingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.clearing_time
     *
     * @param clearingTime the value for t_gh_current_products.clearing_time
     *
     * @mbggenerated
     */
    public void setClearingTime(String clearingTime) {
        this.clearingTime = clearingTime == null ? null : clearingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.cleared_time
     *
     * @return the value of t_gh_current_products.cleared_time
     *
     * @mbggenerated
     */
    public String getClearedTime() {
        return clearedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.cleared_time
     *
     * @param clearedTime the value for t_gh_current_products.cleared_time
     *
     * @mbggenerated
     */
    public void setClearedTime(String clearedTime) {
        this.clearedTime = clearedTime == null ? null : clearedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.deal_start_time
     *
     * @return the value of t_gh_current_products.deal_start_time
     *
     * @mbggenerated
     */
    public String getDealStartTime() {
        return dealStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.deal_start_time
     *
     * @param dealStartTime the value for t_gh_current_products.deal_start_time
     *
     * @mbggenerated
     */
    public void setDealStartTime(String dealStartTime) {
        this.dealStartTime = dealStartTime == null ? null : dealStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.deal_end_time
     *
     * @return the value of t_gh_current_products.deal_end_time
     *
     * @mbggenerated
     */
    public String getDealEndTime() {
        return dealEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.deal_end_time
     *
     * @param dealEndTime the value for t_gh_current_products.deal_end_time
     *
     * @mbggenerated
     */
    public void setDealEndTime(String dealEndTime) {
        this.dealEndTime = dealEndTime == null ? null : dealEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.purchase_people_num
     *
     * @return the value of t_gh_current_products.purchase_people_num
     *
     * @mbggenerated
     */
    public Integer getPurchasePeopleNum() {
        return purchasePeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.purchase_people_num
     *
     * @param purchasePeopleNum the value for t_gh_current_products.purchase_people_num
     *
     * @mbggenerated
     */
    public void setPurchasePeopleNum(Integer purchasePeopleNum) {
        this.purchasePeopleNum = purchasePeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.purchase_num
     *
     * @return the value of t_gh_current_products.purchase_num
     *
     * @mbggenerated
     */
    public Integer getPurchaseNum() {
        return purchaseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.purchase_num
     *
     * @param purchaseNum the value for t_gh_current_products.purchase_num
     *
     * @mbggenerated
     */
    public void setPurchaseNum(Integer purchaseNum) {
        this.purchaseNum = purchaseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.single_day_redeem_count
     *
     * @return the value of t_gh_current_products.single_day_redeem_count
     *
     * @mbggenerated
     */
    public Integer getSingleDayRedeemCount() {
        return singleDayRedeemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.single_day_redeem_count
     *
     * @param singleDayRedeemCount the value for t_gh_current_products.single_day_redeem_count
     *
     * @mbggenerated
     */
    public void setSingleDayRedeemCount(Integer singleDayRedeemCount) {
        this.singleDayRedeemCount = singleDayRedeemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.clearing_operator
     *
     * @return the value of t_gh_current_products.clearing_operator
     *
     * @mbggenerated
     */
    public String getClearingOperator() {
        return clearingOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.clearing_operator
     *
     * @param clearingOperator the value for t_gh_current_products.clearing_operator
     *
     * @mbggenerated
     */
    public void setClearingOperator(String clearingOperator) {
        this.clearingOperator = clearingOperator == null ? null : clearingOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.rec_period_exp_anYield
     *
     * @return the value of t_gh_current_products.rec_period_exp_anYield
     *
     * @mbggenerated
     */
    public BigDecimal getRecPeriodExpAnyield() {
        return recPeriodExpAnyield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.rec_period_exp_anYield
     *
     * @param recPeriodExpAnyield the value for t_gh_current_products.rec_period_exp_anYield
     *
     * @mbggenerated
     */
    public void setRecPeriodExpAnyield(BigDecimal recPeriodExpAnyield) {
        this.recPeriodExpAnyield = recPeriodExpAnyield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.raise_full_found_type
     *
     * @return the value of t_gh_current_products.raise_full_found_type
     *
     * @mbggenerated
     */
    public String getRaiseFullFoundType() {
        return raiseFullFoundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.raise_full_found_type
     *
     * @param raiseFullFoundType the value for t_gh_current_products.raise_full_found_type
     *
     * @mbggenerated
     */
    public void setRaiseFullFoundType(String raiseFullFoundType) {
        this.raiseFullFoundType = raiseFullFoundType == null ? null : raiseFullFoundType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.auto_found_days
     *
     * @return the value of t_gh_current_products.auto_found_days
     *
     * @mbggenerated
     */
    public Integer getAutoFoundDays() {
        return autoFoundDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.auto_found_days
     *
     * @param autoFoundDays the value for t_gh_current_products.auto_found_days
     *
     * @mbggenerated
     */
    public void setAutoFoundDays(Integer autoFoundDays) {
        this.autoFoundDays = autoFoundDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.overdue_status
     *
     * @return the value of t_gh_current_products.overdue_status
     *
     * @mbggenerated
     */
    public String getOverdueStatus() {
        return overdueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.overdue_status
     *
     * @param overdueStatus the value for t_gh_current_products.overdue_status
     *
     * @mbggenerated
     */
    public void setOverdueStatus(String overdueStatus) {
        this.overdueStatus = overdueStatus == null ? null : overdueStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.redeemWithout_interest
     *
     * @return the value of t_gh_current_products.redeemWithout_interest
     *
     * @mbggenerated
     */
    public String getRedeemwithoutInterest() {
        return redeemwithoutInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.redeemWithout_interest
     *
     * @param redeemwithoutInterest the value for t_gh_current_products.redeemWithout_interest
     *
     * @mbggenerated
     */
    public void setRedeemwithoutInterest(String redeemwithoutInterest) {
        this.redeemwithoutInterest = redeemwithoutInterest == null ? null : redeemwithoutInterest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.closing_rule
     *
     * @return the value of t_gh_current_products.closing_rule
     *
     * @mbggenerated
     */
    public String getClosingRule() {
        return closingRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.closing_rule
     *
     * @param closingRule the value for t_gh_current_products.closing_rule
     *
     * @mbggenerated
     */
    public void setClosingRule(String closingRule) {
        this.closingRule = closingRule == null ? null : closingRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.market_state
     *
     * @return the value of t_gh_current_products.market_state
     *
     * @mbggenerated
     */
    public String getMarketState() {
        return marketState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.market_state
     *
     * @param marketState the value for t_gh_current_products.market_state
     *
     * @mbggenerated
     */
    public void setMarketState(String marketState) {
        this.marketState = marketState == null ? null : marketState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.project_id
     *
     * @return the value of t_gh_current_products.project_id
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.project_id
     *
     * @param projectId the value for t_gh_current_products.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.create_time
     *
     * @return the value of t_gh_current_products.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.create_time
     *
     * @param createTime the value for t_gh_current_products.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gh_current_products.update_time
     *
     * @return the value of t_gh_current_products.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gh_current_products.update_time
     *
     * @param updateTime the value for t_gh_current_products.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}