package com.shanghai.dao.ext;

import com.shanghai.domain.UserDomain;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface UserDomainExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 28 17:27:37 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 28 17:27:37 CST 2017
     */
    int insert(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 28 17:27:37 CST 2017
     */
    int insertSelective(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 28 17:27:37 CST 2017
     */
    UserDomain selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 28 17:27:37 CST 2017
     */
    int updateByPrimaryKeySelective(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 28 17:27:37 CST 2017
     */
    int updateByPrimaryKey(UserDomain record);

    List<UserDomain> listUser();
}